M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 15, Monday 13:16:43
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-15T13:16:43+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X0.8398Y-0.9618
X0.8398Y-1.1894
T2
X0.8445Y-1.4949
X1.1594Y-1.4949
T0
M30
