M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 12, Wednesday 10:26:12
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-12T10:26:12+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X0.9762Y-0.5282
X0.9762Y-1.6307
X1.2038Y-0.5282
X1.2038Y-1.6307
T0
M30
