M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 29, Saturday 19:14:39
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-29T19:14:39+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X1.0362Y-0.5182
X1.0362Y-1.6407
X1.2638Y-0.5182
X1.2638Y-1.6407
T0
M30
